services:
  - type: web
    name: real-estate-api
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: bundle exec ruby app.rb
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: PORT
        value: 4000
    envVarGroups:
      - name: database
        envVars:
          - key: DATABASE_URL
            fromDatabase:
              name: real-estate-db
              property: connectionString
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
    routes:
      - type: rewrite
        source: /
        destination: /api/v1

databases:
  - name: real-estate-db
    databaseName: realestate
    user: realestate
    plan: free 